spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Hl_19980521
    url: jdbc:mysql://localhost:3306/my_database?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    showsql: true